# Generated by Django 4.1.4 on 2023-06-17 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudyGuidelinePortal', '0002_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonWatchTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watch_time', models.TextField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyGuidelinePortal.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
