# Generated by Django 4.1.4 on 2023-06-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0003_alter_lesson_views_lessonwatchtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_tags',
            field=models.TextField(default=''),
        ),
    ]
