# Generated by Django 4.1.4 on 2023-06-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0004_lesson_lesson_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
