# Generated by Django 4.1.4 on 2023-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0005_lesson_lesson_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_summary',
            field=models.CharField(default='', max_length=500),
        ),
    ]
