# Generated by Django 4.1.4 on 2023-07-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0007_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
