# Generated by Django 4.1.4 on 2023-08-14 12:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0008_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_pic', models.ImageField(default=None, null=True, upload_to='images/course/')),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_name', unique=True)),
                ('department', models.ManyToManyField(default=None, to='StudyGuidelinePortal.department')),
            ],
        ),
    ]
