# Generated by Django 4.1.4 on 2023-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0009_mycourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.DeleteModel(
            name='MyCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(default=None, to='StudyGuidelinePortal.department'),
        ),
    ]
