# Generated by Django 4.1.4 on 2023-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0010_remove_course_department_delete_mycourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_summary',
            field=models.TextField(default=''),
        ),
    ]
