# Generated by Django 4.1.4 on 2023-08-24 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0011_alter_lesson_lesson_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
