# Generated by Django 4.1.4 on 2023-09-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0013_youtubevideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideos',
            name='video_title',
            field=models.TextField(default=''),
        ),
    ]
