# Generated by Django 4.1.4 on 2023-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0014_youtubevideos_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideos',
            name='video_title',
            field=models.TextField(),
        ),
    ]
