# Generated by Django 4.1.4 on 2023-10-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0015_alter_youtubevideos_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideos',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
