# Generated by Django 4.1.4 on 2023-10-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyGuidelinePortal', '0016_rename_lesson_id_youtubevideos_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_ans', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyGuidelinePortal.query')),
            ],
        ),
    ]
